apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.images.migrate.repository }}:{{ .Values.images.migrate.tag }}"
          imagePullPolicy: {{ .Values.images.migrate.pullPolicy }}
          env:
            - name: LUPERCAL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.postgres }}
                  key: database-url
          resources:
            {{- toYaml .Values.resources.migrate | nindent 12 }}
